# Generated by Django 4.2.7 on 2024-02-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertiesmodel',
            name='propertyDataType',
            field=models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('float', 'Decimal'), ('date', 'Date')], default='str', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertiesmodel',
            name='propertyRequired',
            field=models.BooleanField(default=False),
        ),
    ]
